In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv(r"new_cuisine.csv", encoding='UTF-8')

In [ ]:
data = df.iloc[:,[0,4]]
data.tail()

             DishName                           DishType
150  Chocolate Pastry         desserts, side dish, sweet
151       Malai Kulfi          desserts, side dish, cold
152       Shahi Tukda        desserts, side dish,sweeet,
153      Carrot Halwa  desserts, side dish, halwa, sweet
154  Moong daal Halwa  desserts, side dish, halwa, sweet

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfidf = TfidfVectorizer(stop_words="english")

In [ ]:
tfidf_matrix = tfidf.fit_transform(data["DishType"])

In [ ]:
from sklearn.metrics.pairwise import linear_kernel

In [ ]:
cos_sim_matrix = linear_kernel(tfidf_matrix, tfidf_matrix)

In [ ]:
data_index = pd.Series(data.index, index =data["DishName"]).drop_duplicates()

In [ ]:
def find_food(Name, topN):
  data_id = data_index[Name]
  cosine_scores = list(enumerate(cos_sim_matrix[data_id]))
  cosine_scores = sorted(cosine_scores, key = lambda x:x[1], reverse = True)
  cosine_scores_N = cosine_scores[0: topN+1]
  data_idx = [i[0] for i in cosine_scores_N]
  data_scores = [i[1] for i in cosine_scores_N]
  
  data_similar = pd.DataFrame(columns = ["DishName","Scores"])
  data_similar["DishName"] = data.loc[data_idx, "DishName"]
  data_similar["Scores"] = data_scores

  print(data_similar)

In [ ]:
find_food("Mysore Bonda", topN = 10)

          DishName    Scores
4     Mysore Bonda  1.000000
13         Paratha  0.811810
10       Idiyappam  0.782631
6   Only Pesarattu  0.685123
8           Pongal  0.661735
14    Methi Thepla  0.648595
15     Poori Bhaji  0.648595
3             Dosa  0.590410
9            Appam  0.580975
11         Parotta  0.576119
16            Poha  0.469657

In [ ]:
find_food("Veg Cutlet", topN =10)

            DishName    Scores
22        Veg Cutlet  1.000000
39    Veg Manchurian  0.593394
43   Chilli Mushroom  0.584488
23     Veg Dumplings  0.579886
38  Veg Spring Rolls  0.552068
44     Chilli Paneer  0.523690
41         Baby Corn  0.506590
24        Veg Pakora  0.469824
90         Veg Kofta  0.429360
97     Mix Veg Curry  0.429360
27       Seekh Kabab  0.401321

In [ ]:
import pickle

In [ ]:
pickle.dump(data, open('food.pkl','wb'))

In [ ]:
pickle.dump(cos_sim_matrix, open('similarity.pkl','wb'))